version: '3'
services:
  server:
    build: .
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
    volumes:
      - ./:/repo
      - /repo/node_modules
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'pokemon'
