version: '3'
services:
  client:
    command: npm run watch
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
  server:
    command: npm run start:dev
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    volumes:
      - ./:/app
      - /app/node_modules
