version: '3'
services:
  server:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/repo
    depends_on:
      - redis
  redis:
    image: 'redis:alpine'
    hostname: redis
    ports:
      - '6379:6379'
