version: '3'
services:
  client:
    command: yarn run watch
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - server
  server:
    command: yarn run dev
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    volumes:
      - ./:/app
      - /app/node_modules
